package me.randomhashtags.randompackage.utils.enums;

public enum Feature {
    AUCTION_HOUSE, BOOSTERS, CHAT_BRAG, COINFLIP, COLLECTION_FILTER, CONQUEST,
    CUSTOM_ARMOR, CUSTOM_BOSSES, CUSTOM_ENCHANTS, CUSTOM_CREEPERS, CUSTOM_TNT,
    DUELS, DUNGEONS, ENVOY, FACTION_UPGRADES, FUND, GLOBAL_CHALLENGES,
    HOMES, ITEM_FILTER, JACKPOT,
    KITS_EVOLUTION, KITS_GLOBAL, KITS_MASTERY,
    KOTH, LAST_MAN_STANDING, LOOTBOXES, MASKS, MOB_STACKER, MONTHLY_CRATES,
    OUTPOSTS, PLAYER_QUESTS, PETS,
    SECONDARY_EVENTS, SERVER_CRATES, SHOP, SHOWCASE, TITLES, TRADE, TRINKETS, WILD_PVP,
}
